---
# handlers file for elasticsearch
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: restart elasticsearch
  systemd:
    name: elasticsearch
    enabled: yes
    state: restarted
  become: yes